# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88e9350afb9bbeff65530480007aaf363c38339799d866247e3149543ac9a827c51c335901bb32a313dfd30f5681ab3694c8127d14aed2b0d9503eca1aee1ad3

test:
  secret_key_base: 5603363ee9a81fce5a7a7ee41303fa60d39f4a5fcf454d1635c7c92adcc7fef3a9ec100e2c7b77eaf9c86ce521ea3dbf87000d8dfb81f8314db824374ce3802d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
